### ISSUE TITLE
Search users by tech

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#102]
Search userbase by people who know X, where X is a tech present in the tech field of a user (specified on the profile page)

**Comment by kmcnellis** [comment]
@vkr96 Any update on this?

**Comment by nickkoul** [comment]
Is there functionality to search user by name already? If not should we do that as well?

**Comment by aeksco** [comment]
Tracking this issue in [Observatory-Client #31](https://github.com/rcos/observatory-client/issues/31) - closing.
