### ISSUE TITLE
Account management - edit Github link

### ISSUE THREAD

**Issue by jzblee** [rcos/Observatory3#131]
Users should be able to edit their GitHub link via the settings page, in case it is entered incorrectly during registration.

**Comment by kmcnellis** [comment]
@nickkoul Any update?  If you're not working on it currently, you can unassign yourself.

**Comment by nickkoul** [comment]
I already fixed this and it was merged. I am not sure if it got put under another issue but I think we can close this.

**Comment by kmcnellis** [comment]
Ok, thanks
