### ISSUE TITLE
RCOS "Starter/Default Projects"

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#136]
Admins should be able to mark projects in RCOS as "Starter" or "Default", these projects are intended for users who just join RCOS to join.

There should be a button on the projects page "Mark Default"/"Unmark Default" that toggles a project's status.

**Comment by seveibar** [comment]
Can we get a status update for this? It needs to be done soon

**Comment by zlalvani** [comment]
I think I'm about halfway done

**Comment by vkr96** [comment]
So is a starter project a project anybody could join?

**Comment by seveibar** [comment]
Yes, it's also a project that you're automatically assigned to if you can't find a project.
