### ISSUE TITLE
Blank user profile looks bad

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#141]
Need a way to make the user profile page look better when user hasn't filled out any info.

**Comment by seveibar** [comment]
Similar to looking at an empty github repository, a message should be displayed like "This user hasn't added any tags" or something of the like

**Comment by nickkoul** [comment]
Do you want anything other then default text before anything has been filled out?

**Comment by seveibar** [comment]
Things like tags should display "This user has not placed any tags"
