### ISSUE TITLE
Projects images on user profile page

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#146]
Project list should have a default image or show an image from uploads.

**Comment by seveibar** [comment]
Status update @leej42? Feel free to push it to a branch so somebody else can finish up (you have a couple issues)

**Comment by leej42** [comment]
Yeah sorry, so I tried making a default image and just linking to it, but I dont think that it's the best way to do it. I'm going to try and make a new folder on project creation and add the default image. 
What do you think @seveibar @agundy . Any other suggestions on my approach?

**Comment by leej42** [comment]
@seveibar @agundy Hey so I decided to make one default img and on the frontend check if the list is empty and reference it... I'm not sure if you wanted me to do it on the frontend or backend, but this way we only need one copy of the img.

**Comment by kmcnellis** [comment]
@leej42 Any update?

**Comment by kmcnellis** [comment]
Similar to #352

**Comment by kmcnellis** [comment]
fixed in #386
