### ISSUE TITLE
User Page needs a back button 

### ISSUE THREAD

**Issue by vkr96** [rcos/Observatory3#149]
After clicking on a user there's no way to go back on the page you were on. Only way to go back is to press the back button. This only goes back to page 1. Should be a back button on user profile that allows you go back to the page you were viewing.

**Comment by kmcnellis** [comment]
I don't see this. Could you elaborate? (Navigating from projects -> observatory -> a user page, if I click back, it does return to observatory)

**Comment by vkr96** [comment]
If I'm on the third page of the user profiles and click back it goes back to the first page

**Comment by agundy** [comment]
I think we should make use of the Javascript history api on the users and projects pages

**Comment by agundy** [comment]
Closing this but opened #466 which will do what we need
