### ISSUE TITLE
Email not working on live site

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#170]
Just needs configuration tokens

**Comment by agundy** [comment]
this works. Only problem is the email doesn't send the link correctly

**Comment by agundy** [comment]
i got an email but it was to / instead of rcos.io/

**Comment by kmcnellis** [comment]
The response is shown to the user in json 
![screen shot 2016-04-15 at 11 21 24 am](https://cloud.githubusercontent.com/assets/5566205/14566139/42786d32-02fc-11e6-9105-93d00cf80a1a.png)
