### ISSUE TITLE
Can't create a project on the RCOS website

### ISSUE THREAD

**Issue by dwightnaylor** [rcos/Observatory3#172]
I've tried a half a dozen times to make a project on the RCOS website, but it never shows. Does it not work if my github repo is private?

**Comment by agundy** [comment]
First you have to be logged in with an account on rcos.io. If you are logged in and still having this issue I would be interested to know what you were putting in as values. Also as RCOS is open source the repo you add should not be private. We don't actually check that right now though.

**Comment by dwightnaylor** [comment]
Seems like this last one worked out, so nevermind!
