### ISSUE TITLE
Broken Project Page

### ISSUE THREAD

**Issue by astonshane** [rcos/Observatory3#174]
The Eve Online Market Analysis Tool team set up their project page incorrectly, and now clicking on their project or on their blog from the main project page (rcos.io/projects) just redirects to rcos.io. 
As a result, they can't add members to the page or edit their blog.

They fixed this by just creating a new project page.

**Comment by agundy** [comment]
Will look into. Thanks!

**Comment by kmcnellis** [comment]
Duplicate of #190

**Comment by kmcnellis** [comment]
Fixed manually, needs something like #404 to prevent. Duplicate of #353
