### ISSUE TITLE
Edit Project Page

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#190]
Inline editing works for some fields on the project page but there are other fields that can't be editing inline currently such as website, repository and whether the project is active or not.. We should have a project settings page for all your editing needs.

**Comment by bennyty** [comment]
My project HabitRPG used to be at habitrpg.com but is now at habitica.com. +1

**Comment by kmcnellis** [comment]
#174,  #324, #320 are duplicates

**Comment by kmcnellis** [comment]
fixed in #373
