### ISSUE TITLE
Update homepage description link to point to new site

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#200]
Currently the description on the homepage has a sentence 'Our members work on a variety of projects, as can be seen here.' with the 'here' point to the old rcos.rpi.edu projects page instead of the new '/projects'. This link should be updated.

**Comment by aaroncaic** [comment]
Will work on this with my partner in tomorrow's Intro to Open Source (CSCI-2961) lab.

**Comment by agundy** [comment]
Awesome thanks! Let me know if you need help!
