### ISSUE TITLE
Should be a test for adding a project successfully

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#204]
in '/server/api/project/project.spec.js' there are no tests for adding a new project. For this issue add a test that successfully adds a project via the API.

**Comment by MonkStrom** [comment]
Barry and Cole got here

**Comment by agundy** [comment]
Here is a great example of how to write a post request, post is just for sending data, http://stackoverflow.com/questions/31176526/how-to-write-a-post-request-test-in-mocha-with-data-to-test-if-response-matches, The code looks a little weird but is callled Mocha and is designed to be human readable.

**Comment by MonkStrom** [comment]
We think we're able to send in project information for a new project (Seve says all we need is a project name). But we're not sure how to get the information for all the projects and check if the test project is there.

**Comment by agunderson** [comment]
For this just check that it returns back to you successfully

**Comment by agunderson** [comment]
Thanks!

**Comment by MonkStrom** [comment]
What kind of http response should we get, 200 or 400? Is authentication needed here?

**Comment by agunderson** [comment]
Authentication is actually needed to add a project. 
Not sure we have examples of authentication adding anywhere...

**Comment by agunderson** [comment]
should return 200. If you leave it as such but the test fails still I wouldn't worry about it. and keep it broken for now and I'll add auth for you later.

**Comment by zmike808** [comment]
This has been marked as closed so I am moving to to completed in the https://github.com/rcos/Observatory3/projects/4#card-1693802 project.
