### ISSUE TITLE
Test for past users list to return an array

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#210]
Write a test in '/server/api/users/users.spec.js' that makes sure past users endpoint returns an array.

**Comment by njbbaer** [comment]
Nathaniel and Haoxin are working on this

**Comment by HaoxinLuo** [comment]
Would copying over the contents of 'server/api/commit/commit.spec.js' to '/server/api/users/users.spec.js' and change "describe('GET /api/commits', function() {" to "describe('GET /api/users', function() {"  and ".get('/api/commits')" on line 11 to ".get('/api/users')" be enough to resovle the issue?

**Comment by agundy** [comment]
yes but you will want the api endpoint to be /api/users/past/
