### ISSUE TITLE
Test for calling the api endpoint for create user with bad info

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#211]
Should refuse reject you. Bad data can be anything from no name to no email to no password/non matching passwords.

**Comment by damemi** [comment]
Mike & Brian

**Comment by agundy** [comment]
To fix this you should add a file /server/api/user/user.spec.js that mirrors server/api/project/project.spec.js but will send a post requests with bad create user credentials, for this class just non matching passwords will be fine.

**Comment by darkmeep** [comment]
We're not sure how to actually send the POST data and what sort of response we should expect if there's an error.

**Comment by damemi** [comment]
What is the url for the api call to create a user? I've tried searching through the code and the best options I can come up with seem like it's either /api/user, /api/user/create, /api/createUser, /auth/createUser, etc. I'm getting a 404 build error when trying these.

**Comment by damemi** [comment]
@agundy any idea on this? Thanks

**Comment by agundy** [comment]
Oops sorry I started replying to this but never finished... the api call is
a post to '/api/user/'
You can see it here:
https://github.com/rcos/Observatory3/blob/master/server/api/user/index.js#L26
And the implementation of that here:
https://github.com/rcos/Observatory3/blob/master/server/api/user/user.controller.js#L191
which is the controller file in the same directory

**Comment by damemi** [comment]
Thanks for the reply. I'm still getting a 404 error when trying to send a post to /api/user though. The exact error during build is:

1) POST /api/user/ should respond with JSON array:
     Error: expected 200 "OK", got 404 "Not Found"

You can see the spec I'm trying to write here: https://github.com/damemi/Observatory3/blob/master/server/api/user/user.spec.js

Any help would be greatly appreciated. Right now what I've written for the test is pretty minimal, I'm just trying to get past this 404

**Comment by agundy** [comment]
Oops I missed an s should be '/api/users/'

**Comment by damemi** [comment]
Yes! Thank you
