### ISSUE TITLE
Attempting to add a project while not authenticated should return a 401

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#212]
Not sure what the exact code it throws is but I'm pretty sure it will throw a 403. Whatever the create a project endpoint throws to a non logged in user is the code we want to test that keeps being given.

**Comment by josroe9595** [comment]
Will be working on for Lab6-CSCI2961

**Comment by agundy** [comment]
`server/api/project/project.spec.js` is where you will be adding a test and it will look like what I commented on in #211

**Comment by kmcnellis** [comment]
{
name: 'Observatory',
description: 'cool project',
repositoryUrl: 'https://github.com/rcos/Observatory3/'
githubUsername: 'rcos',
githubProjectName:
}

**Comment by zmike808** [comment]
Title says that 400 should be returned, but 401 is the proper status code, since HTTP 401 is defined as Unauthorized (http://www.ietf.org/assignments/http-status-codes/http-status-codes.xml). So I will be using that in my test.
