### ISSUE TITLE
Test that a getting another user doesn't have return their attendance

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#213]
Attendance and grades are private data and shouldn't be returned from the server for anyone but the owner. For this please write a test that makes sure that the attendance field is absent from an unauthenticated call.

**Comment by alpha1693** [comment]
Anli & Sumit

**Comment by vkr96** [comment]
@alpha1693 is this done?

**Comment by vkr96** [comment]
Ghost issue has finally been closed. Round of applause for everyone involved.
