### ISSUE TITLE
Hide add project button from users who are not logged in

### ISSUE THREAD

**Issue by jfucci** [rcos/Observatory3#216]
Also needs to be taken care of in the back end (as per issue #161) but the front end change will be a good start

**Comment by agundy** [comment]
This will involve using the Auth functionality. A good example of how this works is in /client/components/navbar/ This change will involve the html and controller file in /client/app/projects/

**Comment by vkr96** [comment]
Yeah I will try and get the backend part in today or sometime over the weekend.
