### ISSUE TITLE
Adding a project should also add the user creating it as a contributor

### ISSUE THREAD

**Issue by kmcnellis** [rcos/Observatory3#218]
There should be a call added to /server/api/project/project.controller.js in the exports.create function to add the project to the user's project list (similar to exports.addProject in /server/api/user/user.controller.js)

**Comment by chocolatemelt** [comment]
Tae & Kevin are working on this (Table 6)

**Comment by parkt2** [comment]
Tae & Kevin (Table 6) will be working on this issue

**Comment by vkr96** [comment]
Did you guys finish?

**Comment by chocolatemelt** [comment]
Oops, my bad - no we didn't, if someone else wants to take up the issue they're free to.
