### ISSUE TITLE
Profile Function Needs to return Correct Data

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#22]
Profile is currently serving some fake data for the front end. Need to update it with actual models later.

**Comment by agundy** [comment]
Does the profile page have fake data on it still?

**Comment by seveibar** [comment]
The only data that is "Fake" is attendance data, so this will be fixed after that merge (should be done in 20-40 min)

**Comment by seveibar** [comment]
Moving this to the second milestone because attendance score isn't necessary for the first release

**Comment by seveibar** [comment]
changed to #138 because it's more relevant
