### ISSUE TITLE
You don't use username for login

### ISSUE THREAD

**Issue by Istyatur** [rcos/Observatory3#272]

**Comment by agundy** [comment]
What's wrong with logging in with email?

**Comment by Istyatur** [comment]
When you create an account it gets tagged with user-name for auto-fill.  You can tell the browser to forget and overwrite, but you shouldn't need to.

**Comment by seveibar** [comment]
Please make the autofill use email

**Comment by seveibar** [comment]
this is lower priority than small group issues (ATM)

**Comment by gitcole** [comment]
Is this issue resolved? It appears to be from what I see.

**Comment by agundy** [comment]
Yes this is resolved
