### ISSUE TITLE
Developers page styling is messed up

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#278]
![image](https://cloud.githubusercontent.com/assets/1910070/11016827/40963cc6-855a-11e5-93ec-2e1e9c3614f8.png)

This may require investigating previous commits to see who/what broke it.

Kiana, I'm assigning you because I remember a PR where you edited some scss.

**Comment by agundy** [comment]
Can we get this fixed ASAP? Its pretty bad.
