### ISSUE TITLE
star a github repo 

### ISSUE THREAD

**Issue by andykais** [rcos/Observatory3#284]
If someone browsing rcos.io sees a project they like, its more likely that they will star it on observatory, rather than go through the trouble of going onto github and starring it there. 

If we all have github accounts linked to our observatory accounts this should be doable

**Comment by vkr96** [comment]
I'll assign jacob to this since he should be a little familar with working with GithubAPI

**Comment by agundy** [comment]
Marking as a won't fix as this is outside the scope of what we want to do. We don't want to mirror github but instead allow for more group collaboration and showcasing for RCOS.
