### ISSUE TITLE
Edit Project Name Permissions

### ISSUE THREAD

**Issue by nickkoul** [rcos/Observatory3#289]
Anyone who is on a project has the ability to edit the project name. Is there a "project leader" who can have that ability instead of everyone in the project?

**Comment by zlalvani** [comment]
How would the project leader be specified?

**Comment by agundy** [comment]
Is this something we need?

**Comment by vkr96** [comment]
I think its expected that if you have someone on your team, that they will not mess around with the name.

**Comment by agundy** [comment]
closing unless someone thinks this is a required feature.
