### ISSUE TITLE
User attendance should allow for bonus and normal codes generated on same day

### ISSUE THREAD

**Issue by kmcnellis** [rcos/Observatory3#305]

**Comment by seveibar** [comment]
why?

**Comment by kmcnellis** [comment]
So that special event can happen on the same calendar day as a meeting.

**Comment by seveibar** [comment]
Okay thanks

**Comment by kmcnellis** [comment]
Mostly done in https://github.com/rcos/Observatory3/pull/308

**Comment by Bad-Science** [comment]
This appears to still be an issue, I was only able to create a small group bonus session code after the friday meeting, and we were unable to give attendance.
