### ISSUE TITLE
Better way to see all projects 

### ISSUE THREAD

**Issue by vkr96** [rcos/Observatory3#323]
I think we should implement a view model like the one we have for developers where are there a couple pages for the projects instead of having all the projects just all listed in one big list.

**Comment by seveibar** [comment]
+1

**Comment by seveibar** [comment]
It would be nice to get @nickkoul's search function on the project page.

**Comment by kmcnellis** [comment]
We also should put a picture up

**Comment by agundy** [comment]
So we have added sorting, search, and a few other features to the projects page since this was opened. If new features are desired lets open a new issue.
