### ISSUE TITLE
Can't figure out how to change my project's website

### ISSUE THREAD

**Issue by dwightnaylor** [rcos/Observatory3#324]
www.google.com isn't really good for us anymore.

We'd rather have tinyurl.com/moaprcos

**Comment by seveibar** [comment]
Hey @vkr96 could you look at this? I know you made some changes with editting projects (or was that profiles?)

**Comment by vkr96** [comment]
Okey dokey

**Comment by seveibar** [comment]
thanks :)

**Comment by bennyty** [comment]
Any PR that closes this should also close issue #320.

**Comment by kmcnellis** [comment]
Duplicate of #190

**Comment by agundy** [comment]
Fixed.
