### ISSUE TITLE
Project page markdown rendering problem

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#337]
![screenshot 2016-02-12 at 4 23 00 pm](https://cloud.githubusercontent.com/assets/2281120/13020750/17ba24e2-d1a5-11e5-9c18-dd00cb400964.png)
See screenshot. Works fine on the actual project page.

**Comment by gitcole** [comment]
can i get the md file to test this?

**Comment by gitcole** [comment]
nvm just copied the HTML

**Comment by gitcole** [comment]
![formatting_fixed](https://cloud.githubusercontent.com/assets/14129488/14585018/5b542d4c-0431-11e6-9eab-373672d81835.png)

**Comment by kmcnellis** [comment]
Seems to be fixed.
