### ISSUE TITLE
Register Page Log-In Button

### ISSUE THREAD

**Issue by sschatts** [rcos/Observatory3#348]
Once the register page is filed out and the user clicks the 'Log in' button the email is not actually registered. On the Login Page says the given email is not registered. The user has to click the Register Button after filling out the register page instead of login. These buttons seem to be a toggle between the Login page and Register Page but is confusing which is the correct button to press after filling out the Registration Form.

**Comment by agundy** [comment]
I agree that this isn't the best ux decision. Have a suggestion for what you would rather see?

**Comment by sschatts** [comment]
The easiest would be to remove the login button from the Register Page. If the user by accident clicked the register button from the login page they can get back to the login page by clicking the Login button on the navigation bar. How does that sound?
