### ISSUE TITLE
Project titles with '/' character not escaped

### ISSUE THREAD

**Issue by toshipiazza** [rcos/Observatory3#353]
If we add a project with a / in it, then the link for it is clearly invalid. We also cannot edit the project to delete it as a result...

Example: project name: `Myo-Intelligesture/`
profile link: `https://rcos.io/projects/VoidingWarranties/Myo-Intelligesture//profile`

**Comment by agundy** [comment]
Ah sorry about that good catch. I will manually update it for you for now

**Comment by toshipiazza** [comment]
Cool, thanks! I already have a Myo-Intelligesture project, you just need to delete the Myo-Intelligesture/ one.

Thanks!

**Comment by kmcnellis** [comment]
Should also add regex to ensure that the github name and project name are allowable.

**Comment by kmcnellis** [comment]
Fixed in #467

**Comment by yongabyte** [comment]
close by #467
