### ISSUE TITLE
All mentor-specific small group permissions can be executed by mentees

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#354]
Mentees can remove group leaders and generate day codes if they go to `/smallgroup`

**Comment by TheoBr** [comment]
Can confirm, a mentee removed me from my group

**Comment by agundy** [comment]
Removed options from UI. Will be removing from api endpoints shortly

**Comment by vkr96** [comment]
@agundy  was this fixed?

**Comment by agundy** [comment]
Not yet. Will do this. Gotta do operating systems hw first
