### ISSUE TITLE
No Save Button on "Edit Profile" Page 

### ISSUE THREAD

**Issue by JohnBehnke** [rcos/Observatory3#426]
There appears to not be a save button on the edit profile page. I'm using Safari. 

<img width="1093" alt="screen shot 2016-04-22 at 5 08 45 pm" src="https://cloud.githubusercontent.com/assets/5631869/14754979/e91260a2-08ac-11e6-9ae3-5dd0d12ab957.png">

**Comment by agundy** [comment]
Something broke 😢 will look into this. Thanks for the issue

**Comment by kmcnellis** [comment]
fixed in #432
