### ISSUE TITLE
Project repository doesn't update

### ISSUE THREAD

**Issue by toshipiazza** [rcos/Observatory3#428]
I tried updating the Myo-Intelligesture main repository (we now own a privately maintained repo since the original repo owner doesn't have time to respond to our pull requests just now), and even though I have updated them in the project settings, the main Repository button has not been updated to reflect this.

In other words...
On https://rcos.io/projects/sashashin/Myo-Intelligesture/profile, if you click on the Repository button, it still says https://github.com/VoidingWarranties/Myo-Intelligesture. Though as you can see, the rcos.io url says sashashin correctly, as I updated it to be.

**Comment by bennyty** [comment]
This is still a bug. [GLS](https://rcos.io/projects/highschoolhacking/gls/profile) was previously at https://github.com/JoshuaKGoldberg/Prototype-General-Language-Syntax-Compiler-CPlusPlus and moved to https://github.com/HighSchoolHacking/GLS/ but the repo button does not update. The website button does update.

**Comment by agundy** [comment]
@jessamarie if you have any questions let me know!

**Comment by jessamarie** [comment]
@agundy Sorry, it took me so long just to do that simple task! I've been swamped the last few days. I'm am definitely going to give the updating issue a go.

**Comment by agundy** [comment]
All good! We all get busy once in a while
