### ISSUE TITLE
Multiple Repositories per Project

### ISSUE THREAD

**Issue by toshipiazza** [rcos/Observatory3#429]
I cannot add multiple repos to a single project, though I believe I should be able to by clicking `Edit Project > Additional Repositories [+]`, but this seems not to do anything. I'm assuming that registering the right repos on RCOS.io is important for the end of the semester for Moorthy, and right now only a half of our work is represented. I put a notice on our blog with the right links so this isn't really game-breaking for us, but for later semesters this could really hurt an RCOS project.

**Comment by agundy** [comment]
Will look into this. Was definitely working before but with lot's of new updates a bug may have slipped in.

**Comment by JoeIaquinto** [comment]
Noticed this as well today when trying to add my second repo to see the recent commits in the feed.

**Comment by jessamarie** [comment]
fixed in #525

**Comment by jessamarie** [comment]
@JoeIaquinto just finished! New changes should be added in the next deployment.
