### ISSUE TITLE
cannot search users on mobile

### ISSUE THREAD

**Issue by andykais** [rcos/Observatory3#433]
Android `Lollipop` Chrome `v49.0.2623.105` cannot select the search box to find a specific user

also minor note, the buttons dont quite respond correctly to the small screen size
<img src="https://cloud.githubusercontent.com/assets/6627147/14857303/164322a8-0c9c-11e6-83c1-3eebb1ae0450.png" width=250>

**Comment by agundy** [comment]
That is really strange. Will investigate
