### ISSUE TITLE
Bio paragraphs might overflow horizontally

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [rcos/Observatory3#437]
Seems to be a result of the `white-space:pre;` in `<div style="white-space:pre;" btf-markdown="user.bio">`. Removing that fixed the bug.

![image](https://cloud.githubusercontent.com/assets/3335181/16702961/61783fa0-451e-11e6-922e-c0005b8da3dd.png)

**Comment by agundy** [comment]
Hmm. Not sure why we have that styling in the first place. Will see if removing that adversely effects anything
