### ISSUE TITLE
Join small group via attendance code

### ISSUE THREAD

**Issue by TheoBr** [rcos/Observatory3#442]
At this moment, a user with no small group entering an attendance code for a small group results in an error. I think it would be logical, especially for meeting 1, if this added them to the small group the code was for

**Comment by agundy** [comment]
ooh. This would be a really nice user experience

**Comment by TheoBr** [comment]
I haven't looked at the the code for attendance much, if you think it's trivial I might crack at it

**Comment by agundy** [comment]
Should be pretty easy. just a reverse lookup

**Comment by agundy** [comment]
The existing controller endpoint is pretty complex but is well commented. https://github.com/rcos/Observatory3/blob/master/server/api/attendance/attendance.controller.js#L297 @kmcnellis wrote a lot of this if you have questions
