### ISSUE TITLE
Users Pagination URL and History

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#466]
Users page has pagination that isn't URL addressable or part of the browser history. I can't look at the third page of users without clicking through every time. If I look at a user profile from page 3 and then hit back I'm on the first page of users again. 

This needs two components:
- Make the pagination a query param on the page
- Add to pages to browser history as users navigate

**Comment by agundy** [comment]
@jessamarie think this might be something you want to dig into next? Might be a little more to bite into but would be a big user improvement

**Comment by jessamarie** [comment]
Hey @agundy, there are only 6 users on the localhost, so I can't even see the page buttons. Is there a way to add many users for testing purposes?

**Comment by agundy** [comment]
@jessamarie you can add as many users as you want to the `server/config/seed/users.json` file. a rerun of grunt seed will then give you all of them!

**Comment by agundy** [comment]
fixed in #486
