### ISSUE TITLE
Attendance should be a non-ambiguous string of numbers and characters.

### ISSUE THREAD

**Issue by luciencd** [rcos/Observatory3#507]
For those with vision problems, or just in general due to the character recognition ambiguity problem, there should be an effort to remove all ambigious characters from the attendance code string.

Like remove l i 1 and O 0.

**Comment by luciencd** [comment]
I can work on this: 
https://github.com/rcos/Observatory3/blob/master/server/api/classyear/classyear.controller.js
just need to modify line 129.

**Comment by kmcnellis** [comment]
Make sure you add it to small groups as well!

**Comment by luciencd** [comment]
Just did.
