### ISSUE TITLE
Attend page should show missed meetings

### ISSUE THREAD

**Issue by cowang4** [rcos/Observatory3#513]
There is no way to see what days you missed attending. I'm thinking of adding this to the attend page. To do so I'll need to crosscheck the Attendance data with the SmallGroup and LargeGroup databases.

**Comment by vkr96** [comment]
Okay, thanks for the help!

**Comment by vkr96** [comment]
@cowang4 hows this going?

**Comment by cowang4** [comment]
Hey. I've put aside some time this Sunday to work on this issue. I've taken a look at it and it seems like I just need to cross reference the SmallGroup and ClassYear dayCodes with the Attendance data in the getAttendance function [here](https://github.com/rcos/Observatory3/blob/master/server/api/attendance/attendance.controller.js#L250). It seems like the Attendance table only has the days that the user has submitted. And there is a SmallGroup model that has a [dayCodes](https://github.com/rcos/Observatory3/blob/239e5c6205414dc9f19538ecee0a66c7c7ab4336/server/api/smallgroup/smallgroup.model.js#L18) object that I can compare to. And the large group dayCodes are in the ClassYear table.
Admittedly I don't have much experience with Web development, so it's slow going.
