### ISSUE TITLE
Recent Commits section only shows commits to master branch

### ISSUE THREAD

**Issue by AaronPerl** [rcos/Observatory3#522]
This is problematic as projects that are developed on many branches with infrequent merges to master will appear to have less progress than they actually do.

**Comment by zmike808** [comment]
This could be solved if we implement our own commit display using our commit model for the data instead of github's RSS feed. Since our commit model will know what commit was in what branch, we could add a filter by branch feature to the UI.

**Comment by kmcnellis** [comment]
This won't be fixed in the current recent commits section. Only a full github integration will fix it.
