### ISSUE TITLE
Extra Large Group Session Showing up on Profile Page

### ISSUE THREAD

**Issue by ferria** [rcos/Observatory3#531]
On my profile page it is saying that I missed a Large Group session although I do not recall having missed any.  The bar is completely green though.
![largegroup](https://cloud.githubusercontent.com/assets/11394178/20117470/c47eb9d8-a5ce-11e6-85cc-3e484e1bac2a.PNG)

**Comment by kmcnellis** [comment]
Its green b/c of the bonus day (8 days + 1 bonus). Its a remnant from not having a bonus requirement.
It looks like someone accidentally added a large group day. I'll fix it.
