### ISSUE TITLE
Edit attendance from Admin/users page

### ISSUE THREAD

**Issue by Bad-Science** [rcos/Observatory3#547]
Not a huge priority, but it would be nice to be able to edit large group, small group, and bonus session attendance through this interface.

**Comment by yongabyte** [comment]
If you meant adding attendances manually on the user page, @SaswatB had that feature implemented recently via #530

**Comment by vkr96** [comment]
The problem is that when he was editing it how to do it was not apparent at all from the UI. 
@Bad-Science were you able to see any sort of button or something like that when you were trying to do this?

**Comment by yongabyte** [comment]
@vkr96 
Sorry I wasn't being very clear. I meant the similar feature has been implemented, but it's not out on the live server yet at that time.
I don't think admins were able to edit any kind attendance on the admin/user page.

**Comment by Bad-Science** [comment]
@vkr96 @yongabyte I did not see the option available but its possible I just don't know what I'm doing.

**Comment by kmcnellis** [comment]
Currently there is only a feature to add manual attendances in the admin panel (and no way to review or remove them)

**Comment by kmcnellis** [comment]
Specifically, we need to now remove attendance

**Comment by yongabyte** [comment]
closed by #657
