### ISSUE TITLE
Image of a project

### ISSUE THREAD

**Issue by mskmoorthy** [rcos/Observatory3#553]
One student in Introduction to Open Source wanted to delete one image of a project.. He is unable to do it (I also tried and could not do)- Is this a problem or our mistake?
Moorthy

**Comment by kmcnellis** [comment]
It seems like the deletePhoto function is no longer working. Could this be a result of #490

**Comment by KNNSpeed** [comment]
Having the same issue. I wasn't sure of the file size/dimensions, so I uploaded some placeholder images to test. Now ReAL has some really silly-looking project images that I can't get rid of (it seems that the first uploaded image is permanently the first one everyone sees)...
