### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by agundy** [rcos/Observatory3#558]
We currently don't have any code coverage information. Would be good to get an idea of the test coverage and encourage more tests to be written.

**Comment by agundy** [comment]
@vkr96 Would this be of interest to you? I know http://gotwarlost.github.io/istanbul/ seemed like a powerful option

**Comment by vkr96** [comment]
This is something that should be implemented, I will look more into this

**Comment by kmcnellis** [comment]
Looks like we already have it!

**Comment by zmike808** [comment]
I ran grunt test:coverage which seems to work. I'm guessing this has already been implemented and someone forgot to close the issue?
