### ISSUE TITLE
Bad Spacing on Home-Page 

### ISSUE THREAD

**Issue by vkr96** [rcos/Observatory3#563]
![spacingwhy](https://cloud.githubusercontent.com/assets/10600418/22388209/658eebe6-e4ad-11e6-9648-a4bfe9a304eb.png)

The buttons should all be vertically aligned. Simple CSS fix.

**Comment by connection-lost** [comment]
The fix I propose is to set a absolute position of the button relative to the beginning of the box. Anyone have better ideas?

**Comment by kmcnellis** [comment]
Yes. There are better ways. I'll take a look at it

**Comment by aeksco** [comment]
I'm going to take ownership of this one - should be a relatively simple fix with flex-box :)
