### ISSUE TITLE
Adding attendance from Admin page adds attendance for wrong date

### ISSUE THREAD

**Issue by kelleyb** [rcos/Observatory3#572]
I attempted to add attendance for myself for 1/27/2017, but it added for 1/26/2017 instead. 

Steps to reproduce: 

- Go to Admin -> users
- Choose a user (ex: Brian Kelley)
- Click the add attendance button
- Choose date. I tested with regular day attendance.
- Submit
- Go to "Attend" page, see the shown for attendance is the day before the one chosen.

**Comment by kmcnellis** [comment]
Seems to be related to GMT/EST. Looking into it
