### ISSUE TITLE
Entering Wrong Attendance Code does not Show any Error

### ISSUE THREAD

**Issue by connection-lost** [rcos/Observatory3#578]
While a user enters a wrong attendance code, he is no longer prompted for "Invalid day code".

The backend reads: `POST /api/attendance/attend 200 18.093 ms - 4`
The frontend page receives an empty response.

**Comment by yongabyte** [comment]
I was able to reproduced it for a while but suddenly it's giving me 400 again. Hope someone could explain it.  
![image](https://cloud.githubusercontent.com/assets/11052440/22724913/998bb22e-ed97-11e6-838f-0586225da71e.png)

**Comment by connection-lost** [comment]
The `Error: Invalid Day Code!` is in the code, but may have some problem going into it.

**Comment by kmcnellis** [comment]
I can't reproduce it

**Comment by yongabyte** [comment]
@connection-lost are you still having this problem?

**Comment by agundy** [comment]
Closing because it doesn't seem to be a current complaint
