### ISSUE TITLE
Improve Faulty Attendance Verification System

### ISSUE THREAD

**Issue by connection-lost** [rcos/Observatory3#615]
A flat 20% (10%?) of attendance verification seems to be a little frustrating, and some factors we are able to consider are:
1. Device's location
2. Type of device
3. Speed of submitting day code (?)

For instance, a desktop device with a geo-ip of Albany does not seem to have a honest attendance...
On the other hand, a laptop device with rpi's subnet ip address submitted the day code in 10 seconds could probably be counted as a valid attendance.

Thoughts? Shall we try improve this system?

**Comment by kmcnellis** [comment]
We can't do most of these, except perhaps making it so that if you submit the code more than 1 hour later, it requires verification. Refiled as #633
