### ISSUE TITLE
Links on homepage

### ISSUE THREAD

**Issue by kmcnellis** [rcos/Observatory3#618]
Make presentation schedule link more prominent
add contact info for coordinators (coordinators@rcos.io)

**Comment by connection-lost** [comment]
This is my current implementation on schedule button, it is located here...
!(m)[http://i.imgur.com/ri62hHO.png]

For contact info for coordinators, how should I describe it? The contact information will be added between "Details" and "Donation" session. Here is something I came up with:
# Contact
For information and inquiry, please email us at (email).

**Comment by connection-lost** [comment]
The e-mail link will look like this:
![m](http://i.imgur.com/lhyzvyv.png)
