### ISSUE TITLE
user page layout broken

### ISSUE THREAD

**Issue by yongabyte** [rcos/Observatory3#630]
![image](https://cloud.githubusercontent.com/assets/11052440/24171968/e91b454e-0e5c-11e7-9b3f-d75feaa739da.png)

**Comment by kmcnellis** [comment]
Can't replicate. Can you try with other browsers and report the results?

**Comment by yongabyte** [comment]
Firefox:
![image](https://cloud.githubusercontent.com/assets/11052440/24316213/b07cbae8-10c2-11e7-9dcd-f75a093183b7.png)

**Comment by aeksco** [comment]
This is likely an issue with Bootstrap 3 - I've marked this a `wontfix` as all client-side development is being handled inside of [observatory-client](https://github.com/rcos/observatory-client) - closing
