### ISSUE TITLE
Profile Image - responsive bugs

### ISSUE THREAD

**Issue by aeksco** [rcos/Observatory3#642]
Medium image isn't circular:
![screenshot 2017-04-11 at 4 52 14 pm](https://cloud.githubusercontent.com/assets/4616233/24930461/6a5cde58-1ebe-11e7-8c26-b6385097fd13.png)

Small image isn't centered:
![screenshot 2017-04-11 at 4 52 23 pm](https://cloud.githubusercontent.com/assets/4616233/24930464/6c4f5cd6-1ebe-11e7-972b-5c23f405741e.png)

**Comment by connection-lost** [comment]
.profile .profile-sidebar img {
    border-radius: 200px;
}

Change to 999px would work?

**Comment by aeksco** [comment]
This issue has been resolved in [observatory-client](https://github.com/rcos/observatory-client) - closing this ticket.
