### ISSUE TITLE
HTML tag works in editing blog posts.

### ISSUE THREAD

**Issue by connection-lost** [rcos/Observatory3#656]
Oh no...
![http://i.imgur.com/Wt3yA2A.png](http://i.imgur.com/Wt3yA2A.png)

(At least <script> does not work)

**Comment by yongabyte** [comment]
We are in the middle of switching to a new blog post editor, see if the problem still occur in the new version of the editor or get a peek of the new editor, check out  #648

**Comment by agundy** [comment]
This is by design.. we treat this field as markdown. Markdown supports html style/size elements. Not an issue.
