### ISSUE TITLE
Refactoring the Client Side to Vue

### ISSUE THREAD

**Issue by chishs** [rcos/Observatory3#661]
Converting from Angular 1 to Vue. Allows for clean code base to add new features/fix bugs.

**Comment by aeksco** [comment]
Related to #671 (Upgrade to Bootstrap 4)   

A UI framework should be selected from the outset to ensure that any custom styles _we_ maintain can be kept to a minimum.

Additionally, it may be worth considering using a CSS naming convention from the outset of that development, to further ensure consistency throughout the client application's codebase. I personally like [BEM](http://getbem.com/) :)

**Comment by aeksco** [comment]
Closing this ticket - current client-side development is now done in the [observatory-client repository](https://github.com/rcos/observatory-client).
