### ISSUE TITLE
Fix existing bugs

### ISSUE THREAD

**Issue by Frankie-guz** [rcos/Observatory3#665]
Small group issues:
https://github.com/rcos/Observatory3/issues/523
 https://github.com/rcos/Observatory3/issues/569

Admin editing users fails:
https://github.com/rcos/Observatory3/issues/567

Bad Spacing on Home-Page https:
//github.com/rcos/Observatory3/issues/563

See the rest on existing bug tagged issues

**Comment by vkr96** [comment]
@Frankie-guz I think this would be more well-served as a milestone rather than as a suite of issues.

**Comment by Frankie-guz** [comment]
Agreed doesn't make sense to have an issue of issues
