### ISSUE TITLE
The ~~strikethrough~~ feature of rcos blog seems not working

### ISSUE THREAD

**Issue by alexZrAl** [rcos/Observatory3#766]
![image](https://user-images.githubusercontent.com/25775899/39212891-0db56518-47de-11e8-9130-60a1bd0aa6f1.png)

**Comment by aeksco** [comment]
Thanks for opening this issue! As it turns out we're going to be pulling blogging features out of Observatory - so I've marked this as a `wontfix` and I'll be closing the issue :)
