### ISSUE TITLE
Reset Password feature is not working

### ISSUE THREAD

**Issue by aeksco** [rcos/Observatory3#768]
Will require a hot-fix to production - I'll be investigating this today...

**Comment by aeksco** [comment]
More details:
```
Request URL: https://rcos.io/api/users/resetPassword
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 188.166.115.244:443
Referrer Policy: no-referrer-when-downgrade
```

Request payload is only: `{ email: 'foo@bar.com' }` - will recreate the issue locally and patch

**Comment by aeksco** [comment]
The request fails here in `user.controller.js` at line `606`:
```
email.sendEmail(user.email, "RCOS.IO Forgot Password", sub, '<br>', filter, function(err, success){
  if (err) return res.status(500).json(err);

  return res.status(200).json(success);
});
```
Looks to be related to SendGrid - could potentially be as simple an expired API key

**Comment by agundy** [comment]
Fixed this. Was missing the Sendgrid Environment variable. created: https://github.com/rcos/observatory-server/issues/785

**Comment by wdturner** [comment]
Nice.

Wes
