### ISSUE TITLE
API routes for Room model

### ISSUE THREAD

**Issue by ratchet12340** [rcos/Observatory3#770]
Here is the specification for a room model. For context on what the functionality will be here, we will have  a listing of the rooms available to RCOS. The small group model will have a reference to the different rooms (where each small group is located).
```
- Room
  - name (string)
  - location (string)
  - capacity (number)
  - wheelchair_accessible (boolean)
```

The role of this issue is to create the needed API routes so that we can do things like add rooms, remove rooms, etc. Here is a list of routes we should have with the associated RESTful verb:

1. Get ALL rooms
2. Get specific room
3. Create a room
4. Update a room's information
5. Delete a room from the database

The API for posts may be a good reference (found in `server/api/post/index.js`).

**Comment by aeksco** [comment]
Resolved
