### ISSUE TITLE
API routes for UrpForm model

### ISSUE THREAD

**Issue by ratchet12340** [rcos/Observatory3#771]
Here is the specification for an UrpForm model. For context on what the functionality will be here, we will have an entry of an UrpForm for each URP form that each student fills out. This way, we will have a big listing of the all the URP forms, and Prof. Goldschmidt can sign off on the whole batch with one click.
```
- UrpForm
  - user_id (ref)
  - semester_id (ref)
  - upload_url (string, references filepath)
```

The role of this issue is to create the needed API routes so that we can do things like get ALL urp forms, delete urp forms, etc. Here is a list of routes we should have with the associated RESTful verb:

1. Get ALL URP forms
2. Get ALL URP forms by semester
2. Get a specific URP form by user & semester
4. Update an URP form (just the URL will need to be updated, probably)
5. Delete an URP form

The API for posts may be a good reference (found in `server/api/post/index.js`).

**Comment by aeksco** [comment]
Resolved
