### ISSUE TITLE
Room model

### ISSUE THREAD

**Issue by ratchet12340** [rcos/Observatory3#773]
Here is the specification for a room model. For context on what the functionality will be here, we will have a listing of the rooms available to RCOS. The small group model will have a reference to the different rooms (where each small group is located).

- Room
  - name (string)
  - location (string)
  - capacity (number)
  - wheelchair_accessible (boolean)

The role of this issue is to create the needed database model so that Mongo will know what properties a 'Room' document should have (basically, just the 4 properties we have above).

The model for posts may be a good reference (found in server/api/post/post.model.js).

**Comment by aeksco** [comment]
Resolved by #777
