### ISSUE TITLE
UserRegistration Routes

### ISSUE THREAD

**Issue by ratchet12340** [rcos/Observatory3#794]
As we are refactoring a lot of the server side to use new models and such, we will look to split the User model into two models:

* User: The User model will focus purely on authentication and user account details
* UserRegistration: This model will focus on things relevant to a student and his/her semester at RCOS.

For reference, this is the preliminary model in mind:
```
  - user_id (ref)
  - project_id (ref)
  - semester_id (ref)
  - rin (string)
  - credits (string)
  - status (string - student, external mentor, alumnus, RPI faculty, etc.)
  - schedule_conflict (boolean)
  - has_completed_urp_form (boolean)
  - requires_wheelchair_accessible_room (boolean)
  - mentor_preferences ([ref])
```

For this issue, please make the rudimentary UserRegistration routes. This will entail making the `index.js` file like before. The following routes should be implemented

* `GET /api/user_registration`
* `POST /api/user_registration`
* `GET /api/user_registration/:userid`
* `PUT /api/user_registration/:id`
* `DELETE /api/user_registration/:userid`

We should probably find UserRegistrations not by the ID of the registration, but by the user since it is heavily tied to one particular user (hence the routes above).

**Comment by aeksco** [comment]
Resolved
