### ISSUE TITLE
Generate API documentation

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#90]
This has got to be possible- it's already confusing navigating this project. We should have some kind of documentation generator so people can maintain this.

**Comment by aeksco** [comment]
We'll be using [APIDocJS](http://apidocjs.com) to auto-generate the server API documentation. The requisite infrastructure is in place - I'll design a template to help developers add documentation to our API controller methods. We'll manage this process on a controller-by-controller basis in smaller tickets so I'll close this issue.
