### ISSUE TITLE
Automatic Project Selection

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#96]
If a user does not have a project, a random Open Source project from a currated list should be used.

**Comment by agundy** [comment]
Not sure we need this for the beta milestone.

**Comment by seveibar** [comment]
I actually will have some parts of this included in my next PR so it should be easy. It's also important for the incoming freshmen this semester.

**Comment by seveibar** [comment]
With the ease of adding projects now, admittedly it isn't a huge feature. But I think it does address a growing RCOS problem.

**Comment by agundy** [comment]
Agreed. Are you pulling projects from active RCOS projects or external?

**Comment by seveibar** [comment]
Projects will be pulled internally, I'll add the large OS projects to the seed

**Comment by seveibar** [comment]
broken up into #136 #137
