### ISSUE TITLE
Mentor dashboard

### ISSUE THREAD

**Issue by seveibar** [rcos/Observatory3#97]
Mentors should be able to see all their mentees ~~password~~ participation.

This may require new fields for mentors (menses).

related to #242

**Comment by natedawg1013** [comment]
Password? Do you mean participation?

**Comment by agundy** [comment]
I'm with Nate on this...

**Comment by seveibar** [comment]
:)

**Comment by seveibar** [comment]
moving to next milestone as it's not necessary for the first influx of users

**Comment by vkr96** [comment]
@seveibar this is done right?

**Comment by seveibar** [comment]
Yes thanks
